name: AWS / MA/MR tests

on:
  schedule:
    - cron: 0 1 * * MON-FRI
  push:
    paths:
      - '.github/workflows/aws-tests-mamr.yml'
      - '.github/workflows/aws-tests1.yml'
#  pull_request:
#    paths:
#      - '.github/workflows/aws-tests-mamr.yml'

env:
  IMAGE_NAME: "localstack/localstack"
  TINYBIRD_DATASOURCE: "community_tests_circleci_ma_mr"

jobs:
  generate-vars:
    name: "Generate random AWS credentials"
    runs-on: ubuntu-latest
    outputs:
      creds: ${{ steps.generate.outputs.creds }}
#      ${{ steps.generate-aws-values.outputs.region }}
#      account_id: ${{ steps.generate-aws-values.outputs.account_id }}
    steps:
      - name: Generate values
        id: generate-aws-values
        run: |
          # Generate a random 12-digit number for TEST_AWS_ACCOUNT_ID
          ACCOUNT_ID=$(shuf -i 100000000000-999999999999 -n 1)
#          echo "account_id=$ACCOUNT_ID" >> $GITHUB_OUTPUT

          # Set TEST_AWS_REGION_NAME to a random AWS region other than us-east-1
          REGIONS=("us-east-2" "us-west-1" "us-west-2" "ap-southeast-2" "ap-northeast-1" "eu-central-1" "eu-west-1")
          REGION=${REGIONS[RANDOM % ${#REGIONS[@]}]}
#          echo "region=$REGION" >> $GITHUB_OUTPUT
          CREDS="${REGION},${ACCOUNT_ID},${ACCOUNT_ID}"
          echo "creds=$CREDS" >> $GITHUB_OUTPUT

  test-ma-mr:
    name: "Run integration tests"
    needs: generate-vars
    uses: ./.github/workflows/aws-tests1.yml
    with:
      disableCaching: ${{ inputs.disableCaching == true }}
      testAWSCredentials: ${{ needs.generate-vars.outputs.creds }}
      PYTEST_LOGLEVEL: ${{ inputs.PYTEST_LOGLEVEL }}
